### ISSUE TITLE
Graph Resize

### ISSUE THREAD

**Issue by peter-bond** [c-f/lel#1]
Graph wird beim ersten öffnen nicht dargestellt. Fenster muss erst geresized werden.

System: Windows 10 -> Chrome / Firefox / Edge

![image](https://user-images.githubusercontent.com/57713475/68764416-f191c500-061a-11ea-9325-e2ed540888f3.png)

**Comment by peter-bond** [comment]
![image](https://user-images.githubusercontent.com/57713475/68768895-a9c36b80-0623-11ea-914a-15c0fd4a2e7c.png)

![image](https://user-images.githubusercontent.com/57713475/68768942-c6f83a00-0623-11ea-8ffb-3de1ef807ef5.png)

**Comment by c-f** [comment]
Thanks for making LeL better. As this is the beta release these bugs might appear. 

The bugfix can be tracked here: https://github.com/c-f/lel/commit/e0982d6aa3557299b1831d397e562fe17910af4a

The binaries for the releases and the docker built was updated and are now ready to go.

## Investigation 
The main reason was that the build container did not use the checked in `package-lock.json` file to pinpoint the versions. 

However this error goes a little deeper and the investigation is not closed yet. It might appear that the dependency antd changes it behaviour between version **3.20.7** and **3.25.1**.
